### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by Alfredbis29**
Play the role of the code reviewer

### CODE REVIEW

**Review by prolajumokeoni — COMMENTED** [review]
Hi @Alfredbis29 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project without a code review performed, kindly perform a review and resubmit 👍🏿 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by prolajumokeoni** [comment]
- [ ] Kindly go through lessons in your dashboard on how to give a [code review](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md) and [review your past project ](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/review_your_project.md)

**Review by BenMukebo — CHANGES_REQUESTED** [review]
## Status: Invalid ❌

### Hi @Alfredbis29 ,

Please fix the issue mentioned below and then request for code review

### Reason

- [ ] I think you have submitted the project without making any review, remember this project is based on reviewing your trial project, as said the previous reviewer, kindly perform a short review of these files and request for another review

#### Please make sure to submit a code review when you are done with the changes that were requested

**Don't worry you still have the same number of requests left as previous.**


Cheers and Happy Coding :clap: :clap: :clap: 

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by Alfredbis29** [comment]
Hello Ben can we have a quick call on Zoom ?

**Review by Alfredbis29 — COMMENTED** [review]
### Hi **@Bisimwa,**

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!

### To highlight 💪🏻

- No linter errors. ✔️  ✔️   
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

**Review by BenMukebo — APPROVED** [review]
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @Alfredbis29** , 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 
- Your review looks professional, Excellent work 😄 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- Your Design looks awesome, keep rocking :rocket: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏💻  

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
